{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.hudifine",
    "module": "hudifine-api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hudifine-api-1.0.0.jar",
          "url": "hudifine-api-1.0.0.jar",
          "size": 185190,
          "sha512": "315c046ba413ed53fb4883fcfaabf19c69b9efd01dd365e729785264de482f8e3bb4ceb9e9ac0be388fa089001f83611ea6bc213dd228fa2243f72d09cc69f9b",
          "sha256": "4a4cd0ee864a8b45f354270a9bfc31d28bb27f7494f0957b16fcaf05dfb03eaa",
          "sha1": "a5743ec9302f786f2c2a096df36383ee2b6a50ad",
          "md5": "6396e4ba83ed66d67cc5d54c3cd5c9ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.145.4+26.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "hudifine-api-1.0.0.jar",
          "url": "hudifine-api-1.0.0.jar",
          "size": 185190,
          "sha512": "315c046ba413ed53fb4883fcfaabf19c69b9efd01dd365e729785264de482f8e3bb4ceb9e9ac0be388fa089001f83611ea6bc213dd228fa2243f72d09cc69f9b",
          "sha256": "4a4cd0ee864a8b45f354270a9bfc31d28bb27f7494f0957b16fcaf05dfb03eaa",
          "sha1": "a5743ec9302f786f2c2a096df36383ee2b6a50ad",
          "md5": "6396e4ba83ed66d67cc5d54c3cd5c9ab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hudifine-api-1.0.0-sources.jar",
          "url": "hudifine-api-1.0.0-sources.jar",
          "size": 58652,
          "sha512": "7b60677f0c37827a82cc53d3a0b37cefa43e9ae929421b2e8442d2c8902d980181595c25e5aca7963a04edfd8f29129581865b1b851a0a3719c84bb770547d00",
          "sha256": "7e0a96b9a0f33c9f52c8938e4b61296d9df7a522b320e112ca3ec294d54184e3",
          "sha1": "fb8b74d11f3bdf2e54c9dce812651294e877668b",
          "md5": "16e9a444fc4836d2698d38499587610d"
        }
      ]
    }
  ]
}
